package network.vonix.isleofberkperformance.internal;

import net.minecraft.resources.ResourceLocation;

/** Bounded client render-resource reuse for paths selected by Isle of Berk. */
public final class RenderResourceCache {
    private RenderResourceCache() {}

    public static ResourceLocation twoArg(String namespace, String path) {
        if (!"isleofberk".equals(namespace)) return new ResourceLocation(namespace, path);
        switch (path) {
            case "animations/dragons/deadly_nadder.animation.json": return RL_ANIMATIONS_DRAGONS_DEADLY_NADDER_ANIMATION_JSON;
            case "animations/dragons/gronckle.animation.json": return RL_ANIMATIONS_DRAGONS_GRONCKLE_ANIMATION_JSON;
            case "animations/dragons/light_fury.animation.json": return RL_ANIMATIONS_DRAGONS_LIGHT_FURY_ANIMATION_JSON;
            case "animations/dragons/night_fury.animation.json": return RL_ANIMATIONS_DRAGONS_NIGHT_FURY_ANIMATION_JSON;
            case "animations/dragons/nightmare.animation.json": return RL_ANIMATIONS_DRAGONS_NIGHTMARE_ANIMATION_JSON;
            case "animations/dragons/skrill.animation.json": return RL_ANIMATIONS_DRAGONS_SKRILL_ANIMATION_JSON;
            case "animations/dragons/speed_stinger.animation.json": return RL_ANIMATIONS_DRAGONS_SPEED_STINGER_ANIMATION_JSON;
            case "animations/dragons/stinger.animation.json": return RL_ANIMATIONS_DRAGONS_STINGER_ANIMATION_JSON;
            case "animations/dragons/terrible_terror.animation.json": return RL_ANIMATIONS_DRAGONS_TERRIBLE_TERROR_ANIMATION_JSON;
            case "animations/dragons/triple_stryke.animation.json": return RL_ANIMATIONS_DRAGONS_TRIPLE_STRYKE_ANIMATION_JSON;
            case "animations/dragons/zippleback.animation.json": return RL_ANIMATIONS_DRAGONS_ZIPPLEBACK_ANIMATION_JSON;
            case "geo/dragons/deadly_nadder.geo.json": return RL_GEO_DRAGONS_DEADLY_NADDER_GEO_JSON;
            case "geo/dragons/gronckle.geo.json": return RL_GEO_DRAGONS_GRONCKLE_GEO_JSON;
            case "geo/dragons/light_fury.geo.json": return RL_GEO_DRAGONS_LIGHT_FURY_GEO_JSON;
            case "geo/dragons/night_fury.geo.json": return RL_GEO_DRAGONS_NIGHT_FURY_GEO_JSON;
            case "geo/dragons/night_light.geo.json": return RL_GEO_DRAGONS_NIGHT_LIGHT_GEO_JSON;
            case "geo/dragons/nightmare.geo.json": return RL_GEO_DRAGONS_NIGHTMARE_GEO_JSON;
            case "geo/dragons/skrill.geo.json": return RL_GEO_DRAGONS_SKRILL_GEO_JSON;
            case "geo/dragons/speed_stinger.geo.json": return RL_GEO_DRAGONS_SPEED_STINGER_GEO_JSON;
            case "geo/dragons/stinger.geo.json": return RL_GEO_DRAGONS_STINGER_GEO_JSON;
            case "geo/dragons/terrible_terror.geo.json": return RL_GEO_DRAGONS_TERRIBLE_TERROR_GEO_JSON;
            case "geo/dragons/terrible_terror_titan_wing.geo.json": return RL_GEO_DRAGONS_TERRIBLE_TERROR_TITAN_WING_GEO_JSON;
            case "geo/dragons/triple_stryke.geo.json": return RL_GEO_DRAGONS_TRIPLE_STRYKE_GEO_JSON;
            case "geo/dragons/zippleback.geo.json": return RL_GEO_DRAGONS_ZIPPLEBACK_GEO_JSON;
            case "textures/dragons/deadly_nadder/barklethorn.png": return RL_TEXTURES_DRAGONS_DEADLY_NADDER_BARKLETHORN_PNG;
            case "textures/dragons/deadly_nadder/bork_week.png": return RL_TEXTURES_DRAGONS_DEADLY_NADDER_BORK_WEEK_PNG;
            case "textures/dragons/deadly_nadder/deadly_nadder.png": return RL_TEXTURES_DRAGONS_DEADLY_NADDER_DEADLY_NADDER_PNG;
            case "textures/dragons/deadly_nadder/flystorm.png": return RL_TEXTURES_DRAGONS_DEADLY_NADDER_FLYSTORM_PNG;
            case "textures/dragons/deadly_nadder/hjaldr.png": return RL_TEXTURES_DRAGONS_DEADLY_NADDER_HJALDR_PNG;
            case "textures/dragons/deadly_nadder/hjarta.png": return RL_TEXTURES_DRAGONS_DEADLY_NADDER_HJARTA_PNG;
            case "textures/dragons/deadly_nadder/kingstail.png": return RL_TEXTURES_DRAGONS_DEADLY_NADDER_KINGSTAIL_PNG;
            case "textures/dragons/deadly_nadder/lethal_lancebeak.png": return RL_TEXTURES_DRAGONS_DEADLY_NADDER_LETHAL_LANCEBEAK_PNG;
            case "textures/dragons/deadly_nadder/scardian.png": return RL_TEXTURES_DRAGONS_DEADLY_NADDER_SCARDIAN_PNG;
            case "textures/dragons/deadly_nadder/seedling_stormpest.png": return RL_TEXTURES_DRAGONS_DEADLY_NADDER_SEEDLING_STORMPEST_PNG;
            case "textures/dragons/deadly_nadder/springshedder.png": return RL_TEXTURES_DRAGONS_DEADLY_NADDER_SPRINGSHEDDER_PNG;
            case "textures/dragons/deadly_nadder/stormfly.png": return RL_TEXTURES_DRAGONS_DEADLY_NADDER_STORMFLY_PNG;
            case "textures/dragons/gronckle/barn.png": return RL_TEXTURES_DRAGONS_GRONCKLE_BARN_PNG;
            case "textures/dragons/gronckle/cheesemonger.png": return RL_TEXTURES_DRAGONS_GRONCKLE_CHEESEMONGER_PNG;
            case "textures/dragons/gronckle/crubble.png": return RL_TEXTURES_DRAGONS_GRONCKLE_CRUBBLE_PNG;
            case "textures/dragons/gronckle/exiled.png": return RL_TEXTURES_DRAGONS_GRONCKLE_EXILED_PNG;
            case "textures/dragons/gronckle/gronckle.png": return RL_TEXTURES_DRAGONS_GRONCKLE_GRONCKLE_PNG;
            case "textures/dragons/gronckle/hjarta.png": return RL_TEXTURES_DRAGONS_GRONCKLE_HJARTA_PNG;
            case "textures/dragons/gronckle/junior_tuffnut_junior.png": return RL_TEXTURES_DRAGONS_GRONCKLE_JUNIOR_TUFFNUT_JUNIOR_PNG;
            case "textures/dragons/gronckle/meatlug.png": return RL_TEXTURES_DRAGONS_GRONCKLE_MEATLUG_PNG;
            case "textures/dragons/gronckle/rubblegrubber.png": return RL_TEXTURES_DRAGONS_GRONCKLE_RUBBLEGRUBBER_PNG;
            case "textures/dragons/gronckle/yawnckle.png": return RL_TEXTURES_DRAGONS_GRONCKLE_YAWNCKLE_PNG;
            case "textures/dragons/light_fury/drottinn.png": return RL_TEXTURES_DRAGONS_LIGHT_FURY_DROTTINN_PNG;
            case "textures/dragons/light_fury/drottinn_grogaldr.png": return RL_TEXTURES_DRAGONS_LIGHT_FURY_DROTTINN_GROGALDR_PNG;
            case "textures/dragons/light_fury/grogaldr.png": return RL_TEXTURES_DRAGONS_LIGHT_FURY_GROGALDR_PNG;
            case "textures/dragons/light_fury/light_fury.png": return RL_TEXTURES_DRAGONS_LIGHT_FURY_LIGHT_FURY_PNG;
            case "textures/dragons/light_fury/sveinn.png": return RL_TEXTURES_DRAGONS_LIGHT_FURY_SVEINN_PNG;
            case "textures/dragons/light_fury/sveinn_grogaldr.png": return RL_TEXTURES_DRAGONS_LIGHT_FURY_SVEINN_GROGALDR_PNG;
            case "textures/dragons/night_fury/albino.png": return RL_TEXTURES_DRAGONS_NIGHT_FURY_ALBINO_PNG;
            case "textures/dragons/night_fury/arsian.png": return RL_TEXTURES_DRAGONS_NIGHT_FURY_ARSIAN_PNG;
            case "textures/dragons/night_fury/karma.png": return RL_TEXTURES_DRAGONS_NIGHT_FURY_KARMA_PNG;
            case "textures/dragons/night_fury/night_fury.png": return RL_TEXTURES_DRAGONS_NIGHT_FURY_NIGHT_FURY_PNG;
            case "textures/dragons/night_fury/sentinel.png": return RL_TEXTURES_DRAGONS_NIGHT_FURY_SENTINEL_PNG;
            case "textures/dragons/night_fury/svartr.png": return RL_TEXTURES_DRAGONS_NIGHT_FURY_SVARTR_PNG;
            case "textures/dragons/night_fury/toothless.png": return RL_TEXTURES_DRAGONS_NIGHT_FURY_TOOTHLESS_PNG;
            case "textures/dragons/night_light/appaloosa.png": return RL_TEXTURES_DRAGONS_NIGHT_LIGHT_APPALOOSA_PNG;
            case "textures/dragons/night_light/ashwing.png": return RL_TEXTURES_DRAGONS_NIGHT_LIGHT_ASHWING_PNG;
            case "textures/dragons/night_light/dart.png": return RL_TEXTURES_DRAGONS_NIGHT_LIGHT_DART_PNG;
            case "textures/dragons/night_light/dusk.png": return RL_TEXTURES_DRAGONS_NIGHT_LIGHT_DUSK_PNG;
            case "textures/dragons/night_light/harlequeen.png": return RL_TEXTURES_DRAGONS_NIGHT_LIGHT_HARLEQUEEN_PNG;
            case "textures/dragons/night_light/iridescence.png": return RL_TEXTURES_DRAGONS_NIGHT_LIGHT_IRIDESCENCE_PNG;
            case "textures/dragons/night_light/leopard.png": return RL_TEXTURES_DRAGONS_NIGHT_LIGHT_LEOPARD_PNG;
            case "textures/dragons/night_light/nightdancer.png": return RL_TEXTURES_DRAGONS_NIGHT_LIGHT_NIGHTDANCER_PNG;
            case "textures/dragons/night_light/pouncer.png": return RL_TEXTURES_DRAGONS_NIGHT_LIGHT_POUNCER_PNG;
            case "textures/dragons/night_light/ruffrunner.png": return RL_TEXTURES_DRAGONS_NIGHT_LIGHT_RUFFRUNNER_PNG;
            case "textures/dragons/night_light/skydancer.png": return RL_TEXTURES_DRAGONS_NIGHT_LIGHT_SKYDANCER_PNG;
            case "textures/dragons/nightmare/bloodroot.png": return RL_TEXTURES_DRAGONS_NIGHTMARE_BLOODROOT_PNG;
            case "textures/dragons/nightmare/burlystorm.png": return RL_TEXTURES_DRAGONS_NIGHTMARE_BURLYSTORM_PNG;
            case "textures/dragons/nightmare/cardinal.png": return RL_TEXTURES_DRAGONS_NIGHTMARE_CARDINAL_PNG;
            case "textures/dragons/nightmare/carnation.png": return RL_TEXTURES_DRAGONS_NIGHTMARE_CARNATION_PNG;
            case "textures/dragons/nightmare/exiled.png": return RL_TEXTURES_DRAGONS_NIGHTMARE_EXILED_PNG;
            case "textures/dragons/nightmare/fanghook.png": return RL_TEXTURES_DRAGONS_NIGHTMARE_FANGHOOK_PNG;
            case "textures/dragons/nightmare/fangmaster.png": return RL_TEXTURES_DRAGONS_NIGHTMARE_FANGMASTER_PNG;
            case "textures/dragons/nightmare/hellebore.png": return RL_TEXTURES_DRAGONS_NIGHTMARE_HELLEBORE_PNG;
            case "textures/dragons/nightmare/hookfang.png": return RL_TEXTURES_DRAGONS_NIGHTMARE_HOOKFANG_PNG;
            case "textures/dragons/nightmare/mountain.png": return RL_TEXTURES_DRAGONS_NIGHTMARE_MOUNTAIN_PNG;
            case "textures/dragons/nightmare/rainbow.png": return RL_TEXTURES_DRAGONS_NIGHTMARE_RAINBOW_PNG;
            case "textures/dragons/nightmare/sunfyre.png": return RL_TEXTURES_DRAGONS_NIGHTMARE_SUNFYRE_PNG;
            case "textures/dragons/nightmare/tsukarion.png": return RL_TEXTURES_DRAGONS_NIGHTMARE_TSUKARION_PNG;
            case "textures/dragons/nightmare/wolfsbane.png": return RL_TEXTURES_DRAGONS_NIGHTMARE_WOLFSBANE_PNG;
            case "textures/dragons/skrill/albino.png": return RL_TEXTURES_DRAGONS_SKRILL_ALBINO_PNG;
            case "textures/dragons/skrill/crimson.png": return RL_TEXTURES_DRAGONS_SKRILL_CRIMSON_PNG;
            case "textures/dragons/skrill/fryrir.png": return RL_TEXTURES_DRAGONS_SKRILL_FRYRIR_PNG;
            case "textures/dragons/skrill/icebane.png": return RL_TEXTURES_DRAGONS_SKRILL_ICEBANE_PNG;
            case "textures/dragons/skrill/moonshock.png": return RL_TEXTURES_DRAGONS_SKRILL_MOONSHOCK_PNG;
            case "textures/dragons/skrill/nemesis.png": return RL_TEXTURES_DRAGONS_SKRILL_NEMESIS_PNG;
            case "textures/dragons/skrill/pickle.png": return RL_TEXTURES_DRAGONS_SKRILL_PICKLE_PNG;
            case "textures/dragons/skrill/skrill.png": return RL_TEXTURES_DRAGONS_SKRILL_SKRILL_PNG;
            case "textures/dragons/skrill/spark.png": return RL_TEXTURES_DRAGONS_SKRILL_SPARK_PNG;
            case "textures/dragons/skrill/spring_storm.png": return RL_TEXTURES_DRAGONS_SKRILL_SPRING_STORM_PNG;
            case "textures/dragons/skrill/stormshadow.png": return RL_TEXTURES_DRAGONS_SKRILL_STORMSHADOW_PNG;
            case "textures/dragons/skrill/tempest.png": return RL_TEXTURES_DRAGONS_SKRILL_TEMPEST_PNG;
            case "textures/dragons/skrill/zen.png": return RL_TEXTURES_DRAGONS_SKRILL_ZEN_PNG;
            case "textures/dragons/stinger/badlands.png": return RL_TEXTURES_DRAGONS_STINGER_BADLANDS_PNG;
            case "textures/dragons/stinger/coastal_predator.png": return RL_TEXTURES_DRAGONS_STINGER_COASTAL_PREDATOR_PNG;
            case "textures/dragons/stinger/kingly.png": return RL_TEXTURES_DRAGONS_STINGER_KINGLY_PNG;
            case "textures/dragons/stinger/mudsmasher.png": return RL_TEXTURES_DRAGONS_STINGER_MUDSMASHER_PNG;
            case "textures/dragons/stinger/sandscorcher.png": return RL_TEXTURES_DRAGONS_STINGER_SANDSCORCHER_PNG;
            case "textures/dragons/stinger/titanstinger.png": return RL_TEXTURES_DRAGONS_STINGER_TITANSTINGER_PNG;
            case "textures/dragons/stinger/wildroar.png": return RL_TEXTURES_DRAGONS_STINGER_WILDROAR_PNG;
            case "textures/dragons/terrible_terror/blar.png": return RL_TEXTURES_DRAGONS_TERRIBLE_TERROR_BLAR_PNG;
            case "textures/dragons/terrible_terror/chomp.png": return RL_TEXTURES_DRAGONS_TERRIBLE_TERROR_CHOMP_PNG;
            case "textures/dragons/terrible_terror/head.png": return RL_TEXTURES_DRAGONS_TERRIBLE_TERROR_HEAD_PNG;
            case "textures/dragons/terrible_terror/iggy.png": return RL_TEXTURES_DRAGONS_TERRIBLE_TERROR_IGGY_PNG;
            case "textures/dragons/terrible_terror/pain.png": return RL_TEXTURES_DRAGONS_TERRIBLE_TERROR_PAIN_PNG;
            case "textures/dragons/terrible_terror/sharpshot.png": return RL_TEXTURES_DRAGONS_TERRIBLE_TERROR_SHARPSHOT_PNG;
            case "textures/dragons/terrible_terror/sneaky.png": return RL_TEXTURES_DRAGONS_TERRIBLE_TERROR_SNEAKY_PNG;
            case "textures/dragons/terrible_terror/terrible_terror.png": return RL_TEXTURES_DRAGONS_TERRIBLE_TERROR_TERRIBLE_TERROR_PNG;
            case "textures/dragons/terrible_terror/terror.png": return RL_TEXTURES_DRAGONS_TERRIBLE_TERROR_TERROR_PNG;
            case "textures/dragons/terrible_terror/titan_wing.png": return RL_TEXTURES_DRAGONS_TERRIBLE_TERROR_TITAN_WING_PNG;
            case "textures/dragons/triple_stryke/blue.png": return RL_TEXTURES_DRAGONS_TRIPLE_STRYKE_BLUE_PNG;
            case "textures/dragons/triple_stryke/boreas.png": return RL_TEXTURES_DRAGONS_TRIPLE_STRYKE_BOREAS_PNG;
            case "textures/dragons/triple_stryke/champion.png": return RL_TEXTURES_DRAGONS_TRIPLE_STRYKE_CHAMPION_PNG;
            case "textures/dragons/triple_stryke/eclipser.png": return RL_TEXTURES_DRAGONS_TRIPLE_STRYKE_ECLIPSER_PNG;
            case "textures/dragons/triple_stryke/nikora_triple_stryke.png": return RL_TEXTURES_DRAGONS_TRIPLE_STRYKE_NIKORA_TRIPLE_STRYKE_PNG;
            case "textures/dragons/triple_stryke/rosethorn.png": return RL_TEXTURES_DRAGONS_TRIPLE_STRYKE_ROSETHORN_PNG;
            case "textures/dragons/triple_stryke/sleuther.png": return RL_TEXTURES_DRAGONS_TRIPLE_STRYKE_SLEUTHER_PNG;
            case "textures/dragons/triple_stryke/spyro.png": return RL_TEXTURES_DRAGONS_TRIPLE_STRYKE_SPYRO_PNG;
            case "textures/dragons/triple_stryke/starstreak.png": return RL_TEXTURES_DRAGONS_TRIPLE_STRYKE_STARSTREAK_PNG;
            case "textures/dragons/triple_stryke/triple_stryke.png": return RL_TEXTURES_DRAGONS_TRIPLE_STRYKE_TRIPLE_STRYKE_PNG;
            case "textures/dragons/zippleback/exiled.png": return RL_TEXTURES_DRAGONS_ZIPPLEBACK_EXILED_PNG;
            case "textures/dragons/zippleback/fart_n_sniff.png": return RL_TEXTURES_DRAGONS_ZIPPLEBACK_FART_N_SNIFF_PNG;
            case "textures/dragons/zippleback/hamfeist.png": return RL_TEXTURES_DRAGONS_ZIPPLEBACK_HAMFEIST_PNG;
            case "textures/dragons/zippleback/hjarta.png": return RL_TEXTURES_DRAGONS_ZIPPLEBACK_HJARTA_PNG;
            case "textures/dragons/zippleback/hodd.png": return RL_TEXTURES_DRAGONS_ZIPPLEBACK_HODD_PNG;
            case "textures/dragons/zippleback/kandy_n_kane.png": return RL_TEXTURES_DRAGONS_ZIPPLEBACK_KANDY_N_KANE_PNG;
            case "textures/dragons/zippleback/leaf_n_bark.png": return RL_TEXTURES_DRAGONS_ZIPPLEBACK_LEAF_N_BARK_PNG;
            case "textures/dragons/zippleback/pistill.png": return RL_TEXTURES_DRAGONS_ZIPPLEBACK_PISTILL_PNG;
            case "textures/dragons/zippleback/purple_n_nurple.png": return RL_TEXTURES_DRAGONS_ZIPPLEBACK_PURPLE_N_NURPLE_PNG;
            case "textures/dragons/zippleback/sandr.png": return RL_TEXTURES_DRAGONS_ZIPPLEBACK_SANDR_PNG;
            case "textures/dragons/zippleback/whip_n_lash.png": return RL_TEXTURES_DRAGONS_ZIPPLEBACK_WHIP_N_LASH_PNG;
            default: return new ResourceLocation(namespace, path);
        }
    }

    public static ResourceLocation oneArg(String value) {
        switch (value) {
            case "isleofberk:textures/dragons/light_fury/blue_glow.png": return RL_ISLEOFBERK_TEXTURES_DRAGONS_LIGHT_FURY_BLUE_GLOW_PNG;
            case "isleofberk:textures/dragons/light_fury/purple_glow.png": return RL_ISLEOFBERK_TEXTURES_DRAGONS_LIGHT_FURY_PURPLE_GLOW_PNG;
            case "isleofberk:textures/dragons/night_fury/night_fury_glow.png": return RL_ISLEOFBERK_TEXTURES_DRAGONS_NIGHT_FURY_NIGHT_FURY_GLOW_PNG;
            case "isleofberk:textures/dragons/night_fury/sentinel_glow.png": return RL_ISLEOFBERK_TEXTURES_DRAGONS_NIGHT_FURY_SENTINEL_GLOW_PNG;
            default: return new ResourceLocation(value);
        }
    }

    private static final ResourceLocation RL_ANIMATIONS_DRAGONS_DEADLY_NADDER_ANIMATION_JSON = new ResourceLocation("isleofberk", "animations/dragons/deadly_nadder.animation.json");
    private static final ResourceLocation RL_ANIMATIONS_DRAGONS_GRONCKLE_ANIMATION_JSON = new ResourceLocation("isleofberk", "animations/dragons/gronckle.animation.json");
    private static final ResourceLocation RL_ANIMATIONS_DRAGONS_LIGHT_FURY_ANIMATION_JSON = new ResourceLocation("isleofberk", "animations/dragons/light_fury.animation.json");
    private static final ResourceLocation RL_ANIMATIONS_DRAGONS_NIGHT_FURY_ANIMATION_JSON = new ResourceLocation("isleofberk", "animations/dragons/night_fury.animation.json");
    private static final ResourceLocation RL_ANIMATIONS_DRAGONS_NIGHTMARE_ANIMATION_JSON = new ResourceLocation("isleofberk", "animations/dragons/nightmare.animation.json");
    private static final ResourceLocation RL_ANIMATIONS_DRAGONS_SKRILL_ANIMATION_JSON = new ResourceLocation("isleofberk", "animations/dragons/skrill.animation.json");
    private static final ResourceLocation RL_ANIMATIONS_DRAGONS_SPEED_STINGER_ANIMATION_JSON = new ResourceLocation("isleofberk", "animations/dragons/speed_stinger.animation.json");
    private static final ResourceLocation RL_ANIMATIONS_DRAGONS_STINGER_ANIMATION_JSON = new ResourceLocation("isleofberk", "animations/dragons/stinger.animation.json");
    private static final ResourceLocation RL_ANIMATIONS_DRAGONS_TERRIBLE_TERROR_ANIMATION_JSON = new ResourceLocation("isleofberk", "animations/dragons/terrible_terror.animation.json");
    private static final ResourceLocation RL_ANIMATIONS_DRAGONS_TRIPLE_STRYKE_ANIMATION_JSON = new ResourceLocation("isleofberk", "animations/dragons/triple_stryke.animation.json");
    private static final ResourceLocation RL_ANIMATIONS_DRAGONS_ZIPPLEBACK_ANIMATION_JSON = new ResourceLocation("isleofberk", "animations/dragons/zippleback.animation.json");
    private static final ResourceLocation RL_GEO_DRAGONS_DEADLY_NADDER_GEO_JSON = new ResourceLocation("isleofberk", "geo/dragons/deadly_nadder.geo.json");
    private static final ResourceLocation RL_GEO_DRAGONS_GRONCKLE_GEO_JSON = new ResourceLocation("isleofberk", "geo/dragons/gronckle.geo.json");
    private static final ResourceLocation RL_GEO_DRAGONS_LIGHT_FURY_GEO_JSON = new ResourceLocation("isleofberk", "geo/dragons/light_fury.geo.json");
    private static final ResourceLocation RL_GEO_DRAGONS_NIGHT_FURY_GEO_JSON = new ResourceLocation("isleofberk", "geo/dragons/night_fury.geo.json");
    private static final ResourceLocation RL_GEO_DRAGONS_NIGHT_LIGHT_GEO_JSON = new ResourceLocation("isleofberk", "geo/dragons/night_light.geo.json");
    private static final ResourceLocation RL_GEO_DRAGONS_NIGHTMARE_GEO_JSON = new ResourceLocation("isleofberk", "geo/dragons/nightmare.geo.json");
    private static final ResourceLocation RL_GEO_DRAGONS_SKRILL_GEO_JSON = new ResourceLocation("isleofberk", "geo/dragons/skrill.geo.json");
    private static final ResourceLocation RL_GEO_DRAGONS_SPEED_STINGER_GEO_JSON = new ResourceLocation("isleofberk", "geo/dragons/speed_stinger.geo.json");
    private static final ResourceLocation RL_GEO_DRAGONS_STINGER_GEO_JSON = new ResourceLocation("isleofberk", "geo/dragons/stinger.geo.json");
    private static final ResourceLocation RL_GEO_DRAGONS_TERRIBLE_TERROR_GEO_JSON = new ResourceLocation("isleofberk", "geo/dragons/terrible_terror.geo.json");
    private static final ResourceLocation RL_GEO_DRAGONS_TERRIBLE_TERROR_TITAN_WING_GEO_JSON = new ResourceLocation("isleofberk", "geo/dragons/terrible_terror_titan_wing.geo.json");
    private static final ResourceLocation RL_GEO_DRAGONS_TRIPLE_STRYKE_GEO_JSON = new ResourceLocation("isleofberk", "geo/dragons/triple_stryke.geo.json");
    private static final ResourceLocation RL_GEO_DRAGONS_ZIPPLEBACK_GEO_JSON = new ResourceLocation("isleofberk", "geo/dragons/zippleback.geo.json");
    private static final ResourceLocation RL_TEXTURES_DRAGONS_DEADLY_NADDER_BARKLETHORN_PNG = new ResourceLocation("isleofberk", "textures/dragons/deadly_nadder/barklethorn.png");
    private static final ResourceLocation RL_TEXTURES_DRAGONS_DEADLY_NADDER_BORK_WEEK_PNG = new ResourceLocation("isleofberk", "textures/dragons/deadly_nadder/bork_week.png");
    private static final ResourceLocation RL_TEXTURES_DRAGONS_DEADLY_NADDER_DEADLY_NADDER_PNG = new ResourceLocation("isleofberk", "textures/dragons/deadly_nadder/deadly_nadder.png");
    private static final ResourceLocation RL_TEXTURES_DRAGONS_DEADLY_NADDER_FLYSTORM_PNG = new ResourceLocation("isleofberk", "textures/dragons/deadly_nadder/flystorm.png");
    private static final ResourceLocation RL_TEXTURES_DRAGONS_DEADLY_NADDER_HJALDR_PNG = new ResourceLocation("isleofberk", "textures/dragons/deadly_nadder/hjaldr.png");
    private static final ResourceLocation RL_TEXTURES_DRAGONS_DEADLY_NADDER_HJARTA_PNG = new ResourceLocation("isleofberk", "textures/dragons/deadly_nadder/hjarta.png");
    private static final ResourceLocation RL_TEXTURES_DRAGONS_DEADLY_NADDER_KINGSTAIL_PNG = new ResourceLocation("isleofberk", "textures/dragons/deadly_nadder/kingstail.png");
    private static final ResourceLocation RL_TEXTURES_DRAGONS_DEADLY_NADDER_LETHAL_LANCEBEAK_PNG = new ResourceLocation("isleofberk", "textures/dragons/deadly_nadder/lethal_lancebeak.png");
    private static final ResourceLocation RL_TEXTURES_DRAGONS_DEADLY_NADDER_SCARDIAN_PNG = new ResourceLocation("isleofberk", "textures/dragons/deadly_nadder/scardian.png");
    private static final ResourceLocation RL_TEXTURES_DRAGONS_DEADLY_NADDER_SEEDLING_STORMPEST_PNG = new ResourceLocation("isleofberk", "textures/dragons/deadly_nadder/seedling_stormpest.png");
    private static final ResourceLocation RL_TEXTURES_DRAGONS_DEADLY_NADDER_SPRINGSHEDDER_PNG = new ResourceLocation("isleofberk", "textures/dragons/deadly_nadder/springshedder.png");
    private static final ResourceLocation RL_TEXTURES_DRAGONS_DEADLY_NADDER_STORMFLY_PNG = new ResourceLocation("isleofberk", "textures/dragons/deadly_nadder/stormfly.png");
    private static final ResourceLocation RL_TEXTURES_DRAGONS_GRONCKLE_BARN_PNG = new ResourceLocation("isleofberk", "textures/dragons/gronckle/barn.png");
    private static final ResourceLocation RL_TEXTURES_DRAGONS_GRONCKLE_CHEESEMONGER_PNG = new ResourceLocation("isleofberk", "textures/dragons/gronckle/cheesemonger.png");
    private static final ResourceLocation RL_TEXTURES_DRAGONS_GRONCKLE_CRUBBLE_PNG = new ResourceLocation("isleofberk", "textures/dragons/gronckle/crubble.png");
    private static final ResourceLocation RL_TEXTURES_DRAGONS_GRONCKLE_EXILED_PNG = new ResourceLocation("isleofberk", "textures/dragons/gronckle/exiled.png");
    private static final ResourceLocation RL_TEXTURES_DRAGONS_GRONCKLE_GRONCKLE_PNG = new ResourceLocation("isleofberk", "textures/dragons/gronckle/gronckle.png");
    private static final ResourceLocation RL_TEXTURES_DRAGONS_GRONCKLE_HJARTA_PNG = new ResourceLocation("isleofberk", "textures/dragons/gronckle/hjarta.png");
    private static final ResourceLocation RL_TEXTURES_DRAGONS_GRONCKLE_JUNIOR_TUFFNUT_JUNIOR_PNG = new ResourceLocation("isleofberk", "textures/dragons/gronckle/junior_tuffnut_junior.png");
    private static final ResourceLocation RL_TEXTURES_DRAGONS_GRONCKLE_MEATLUG_PNG = new ResourceLocation("isleofberk", "textures/dragons/gronckle/meatlug.png");
    private static final ResourceLocation RL_TEXTURES_DRAGONS_GRONCKLE_RUBBLEGRUBBER_PNG = new ResourceLocation("isleofberk", "textures/dragons/gronckle/rubblegrubber.png");
    private static final ResourceLocation RL_TEXTURES_DRAGONS_GRONCKLE_YAWNCKLE_PNG = new ResourceLocation("isleofberk", "textures/dragons/gronckle/yawnckle.png");
    private static final ResourceLocation RL_TEXTURES_DRAGONS_LIGHT_FURY_DROTTINN_PNG = new ResourceLocation("isleofberk", "textures/dragons/light_fury/drottinn.png");
    private static final ResourceLocation RL_TEXTURES_DRAGONS_LIGHT_FURY_DROTTINN_GROGALDR_PNG = new ResourceLocation("isleofberk", "textures/dragons/light_fury/drottinn_grogaldr.png");
    private static final ResourceLocation RL_TEXTURES_DRAGONS_LIGHT_FURY_GROGALDR_PNG = new ResourceLocation("isleofberk", "textures/dragons/light_fury/grogaldr.png");
    private static final ResourceLocation RL_TEXTURES_DRAGONS_LIGHT_FURY_LIGHT_FURY_PNG = new ResourceLocation("isleofberk", "textures/dragons/light_fury/light_fury.png");
    private static final ResourceLocation RL_TEXTURES_DRAGONS_LIGHT_FURY_SVEINN_PNG = new ResourceLocation("isleofberk", "textures/dragons/light_fury/sveinn.png");
    private static final ResourceLocation RL_TEXTURES_DRAGONS_LIGHT_FURY_SVEINN_GROGALDR_PNG = new ResourceLocation("isleofberk", "textures/dragons/light_fury/sveinn_grogaldr.png");
    private static final ResourceLocation RL_TEXTURES_DRAGONS_NIGHT_FURY_ALBINO_PNG = new ResourceLocation("isleofberk", "textures/dragons/night_fury/albino.png");
    private static final ResourceLocation RL_TEXTURES_DRAGONS_NIGHT_FURY_ARSIAN_PNG = new ResourceLocation("isleofberk", "textures/dragons/night_fury/arsian.png");
    private static final ResourceLocation RL_TEXTURES_DRAGONS_NIGHT_FURY_KARMA_PNG = new ResourceLocation("isleofberk", "textures/dragons/night_fury/karma.png");
    private static final ResourceLocation RL_TEXTURES_DRAGONS_NIGHT_FURY_NIGHT_FURY_PNG = new ResourceLocation("isleofberk", "textures/dragons/night_fury/night_fury.png");
    private static final ResourceLocation RL_TEXTURES_DRAGONS_NIGHT_FURY_SENTINEL_PNG = new ResourceLocation("isleofberk", "textures/dragons/night_fury/sentinel.png");
    private static final ResourceLocation RL_TEXTURES_DRAGONS_NIGHT_FURY_SVARTR_PNG = new ResourceLocation("isleofberk", "textures/dragons/night_fury/svartr.png");
    private static final ResourceLocation RL_TEXTURES_DRAGONS_NIGHT_FURY_TOOTHLESS_PNG = new ResourceLocation("isleofberk", "textures/dragons/night_fury/toothless.png");
    private static final ResourceLocation RL_TEXTURES_DRAGONS_NIGHT_LIGHT_APPALOOSA_PNG = new ResourceLocation("isleofberk", "textures/dragons/night_light/appaloosa.png");
    private static final ResourceLocation RL_TEXTURES_DRAGONS_NIGHT_LIGHT_ASHWING_PNG = new ResourceLocation("isleofberk", "textures/dragons/night_light/ashwing.png");
    private static final ResourceLocation RL_TEXTURES_DRAGONS_NIGHT_LIGHT_DART_PNG = new ResourceLocation("isleofberk", "textures/dragons/night_light/dart.png");
    private static final ResourceLocation RL_TEXTURES_DRAGONS_NIGHT_LIGHT_DUSK_PNG = new ResourceLocation("isleofberk", "textures/dragons/night_light/dusk.png");
    private static final ResourceLocation RL_TEXTURES_DRAGONS_NIGHT_LIGHT_HARLEQUEEN_PNG = new ResourceLocation("isleofberk", "textures/dragons/night_light/harlequeen.png");
    private static final ResourceLocation RL_TEXTURES_DRAGONS_NIGHT_LIGHT_IRIDESCENCE_PNG = new ResourceLocation("isleofberk", "textures/dragons/night_light/iridescence.png");
    private static final ResourceLocation RL_TEXTURES_DRAGONS_NIGHT_LIGHT_LEOPARD_PNG = new ResourceLocation("isleofberk", "textures/dragons/night_light/leopard.png");
    private static final ResourceLocation RL_TEXTURES_DRAGONS_NIGHT_LIGHT_NIGHTDANCER_PNG = new ResourceLocation("isleofberk", "textures/dragons/night_light/nightdancer.png");
    private static final ResourceLocation RL_TEXTURES_DRAGONS_NIGHT_LIGHT_POUNCER_PNG = new ResourceLocation("isleofberk", "textures/dragons/night_light/pouncer.png");
    private static final ResourceLocation RL_TEXTURES_DRAGONS_NIGHT_LIGHT_RUFFRUNNER_PNG = new ResourceLocation("isleofberk", "textures/dragons/night_light/ruffrunner.png");
    private static final ResourceLocation RL_TEXTURES_DRAGONS_NIGHT_LIGHT_SKYDANCER_PNG = new ResourceLocation("isleofberk", "textures/dragons/night_light/skydancer.png");
    private static final ResourceLocation RL_TEXTURES_DRAGONS_NIGHTMARE_BLOODROOT_PNG = new ResourceLocation("isleofberk", "textures/dragons/nightmare/bloodroot.png");
    private static final ResourceLocation RL_TEXTURES_DRAGONS_NIGHTMARE_BURLYSTORM_PNG = new ResourceLocation("isleofberk", "textures/dragons/nightmare/burlystorm.png");
    private static final ResourceLocation RL_TEXTURES_DRAGONS_NIGHTMARE_CARDINAL_PNG = new ResourceLocation("isleofberk", "textures/dragons/nightmare/cardinal.png");
    private static final ResourceLocation RL_TEXTURES_DRAGONS_NIGHTMARE_CARNATION_PNG = new ResourceLocation("isleofberk", "textures/dragons/nightmare/carnation.png");
    private static final ResourceLocation RL_TEXTURES_DRAGONS_NIGHTMARE_EXILED_PNG = new ResourceLocation("isleofberk", "textures/dragons/nightmare/exiled.png");
    private static final ResourceLocation RL_TEXTURES_DRAGONS_NIGHTMARE_FANGHOOK_PNG = new ResourceLocation("isleofberk", "textures/dragons/nightmare/fanghook.png");
    private static final ResourceLocation RL_TEXTURES_DRAGONS_NIGHTMARE_FANGMASTER_PNG = new ResourceLocation("isleofberk", "textures/dragons/nightmare/fangmaster.png");
    private static final ResourceLocation RL_TEXTURES_DRAGONS_NIGHTMARE_HELLEBORE_PNG = new ResourceLocation("isleofberk", "textures/dragons/nightmare/hellebore.png");
    private static final ResourceLocation RL_TEXTURES_DRAGONS_NIGHTMARE_HOOKFANG_PNG = new ResourceLocation("isleofberk", "textures/dragons/nightmare/hookfang.png");
    private static final ResourceLocation RL_TEXTURES_DRAGONS_NIGHTMARE_MOUNTAIN_PNG = new ResourceLocation("isleofberk", "textures/dragons/nightmare/mountain.png");
    private static final ResourceLocation RL_TEXTURES_DRAGONS_NIGHTMARE_RAINBOW_PNG = new ResourceLocation("isleofberk", "textures/dragons/nightmare/rainbow.png");
    private static final ResourceLocation RL_TEXTURES_DRAGONS_NIGHTMARE_SUNFYRE_PNG = new ResourceLocation("isleofberk", "textures/dragons/nightmare/sunfyre.png");
    private static final ResourceLocation RL_TEXTURES_DRAGONS_NIGHTMARE_TSUKARION_PNG = new ResourceLocation("isleofberk", "textures/dragons/nightmare/tsukarion.png");
    private static final ResourceLocation RL_TEXTURES_DRAGONS_NIGHTMARE_WOLFSBANE_PNG = new ResourceLocation("isleofberk", "textures/dragons/nightmare/wolfsbane.png");
    private static final ResourceLocation RL_TEXTURES_DRAGONS_SKRILL_ALBINO_PNG = new ResourceLocation("isleofberk", "textures/dragons/skrill/albino.png");
    private static final ResourceLocation RL_TEXTURES_DRAGONS_SKRILL_CRIMSON_PNG = new ResourceLocation("isleofberk", "textures/dragons/skrill/crimson.png");
    private static final ResourceLocation RL_TEXTURES_DRAGONS_SKRILL_FRYRIR_PNG = new ResourceLocation("isleofberk", "textures/dragons/skrill/fryrir.png");
    private static final ResourceLocation RL_TEXTURES_DRAGONS_SKRILL_ICEBANE_PNG = new ResourceLocation("isleofberk", "textures/dragons/skrill/icebane.png");
    private static final ResourceLocation RL_TEXTURES_DRAGONS_SKRILL_MOONSHOCK_PNG = new ResourceLocation("isleofberk", "textures/dragons/skrill/moonshock.png");
    private static final ResourceLocation RL_TEXTURES_DRAGONS_SKRILL_NEMESIS_PNG = new ResourceLocation("isleofberk", "textures/dragons/skrill/nemesis.png");
    private static final ResourceLocation RL_TEXTURES_DRAGONS_SKRILL_PICKLE_PNG = new ResourceLocation("isleofberk", "textures/dragons/skrill/pickle.png");
    private static final ResourceLocation RL_TEXTURES_DRAGONS_SKRILL_SKRILL_PNG = new ResourceLocation("isleofberk", "textures/dragons/skrill/skrill.png");
    private static final ResourceLocation RL_TEXTURES_DRAGONS_SKRILL_SPARK_PNG = new ResourceLocation("isleofberk", "textures/dragons/skrill/spark.png");
    private static final ResourceLocation RL_TEXTURES_DRAGONS_SKRILL_SPRING_STORM_PNG = new ResourceLocation("isleofberk", "textures/dragons/skrill/spring_storm.png");
    private static final ResourceLocation RL_TEXTURES_DRAGONS_SKRILL_STORMSHADOW_PNG = new ResourceLocation("isleofberk", "textures/dragons/skrill/stormshadow.png");
    private static final ResourceLocation RL_TEXTURES_DRAGONS_SKRILL_TEMPEST_PNG = new ResourceLocation("isleofberk", "textures/dragons/skrill/tempest.png");
    private static final ResourceLocation RL_TEXTURES_DRAGONS_SKRILL_ZEN_PNG = new ResourceLocation("isleofberk", "textures/dragons/skrill/zen.png");
    private static final ResourceLocation RL_TEXTURES_DRAGONS_STINGER_BADLANDS_PNG = new ResourceLocation("isleofberk", "textures/dragons/stinger/badlands.png");
    private static final ResourceLocation RL_TEXTURES_DRAGONS_STINGER_COASTAL_PREDATOR_PNG = new ResourceLocation("isleofberk", "textures/dragons/stinger/coastal_predator.png");
    private static final ResourceLocation RL_TEXTURES_DRAGONS_STINGER_KINGLY_PNG = new ResourceLocation("isleofberk", "textures/dragons/stinger/kingly.png");
    private static final ResourceLocation RL_TEXTURES_DRAGONS_STINGER_MUDSMASHER_PNG = new ResourceLocation("isleofberk", "textures/dragons/stinger/mudsmasher.png");
    private static final ResourceLocation RL_TEXTURES_DRAGONS_STINGER_SANDSCORCHER_PNG = new ResourceLocation("isleofberk", "textures/dragons/stinger/sandscorcher.png");
    private static final ResourceLocation RL_TEXTURES_DRAGONS_STINGER_TITANSTINGER_PNG = new ResourceLocation("isleofberk", "textures/dragons/stinger/titanstinger.png");
    private static final ResourceLocation RL_TEXTURES_DRAGONS_STINGER_WILDROAR_PNG = new ResourceLocation("isleofberk", "textures/dragons/stinger/wildroar.png");
    private static final ResourceLocation RL_TEXTURES_DRAGONS_TERRIBLE_TERROR_BLAR_PNG = new ResourceLocation("isleofberk", "textures/dragons/terrible_terror/blar.png");
    private static final ResourceLocation RL_TEXTURES_DRAGONS_TERRIBLE_TERROR_CHOMP_PNG = new ResourceLocation("isleofberk", "textures/dragons/terrible_terror/chomp.png");
    private static final ResourceLocation RL_TEXTURES_DRAGONS_TERRIBLE_TERROR_HEAD_PNG = new ResourceLocation("isleofberk", "textures/dragons/terrible_terror/head.png");
    private static final ResourceLocation RL_TEXTURES_DRAGONS_TERRIBLE_TERROR_IGGY_PNG = new ResourceLocation("isleofberk", "textures/dragons/terrible_terror/iggy.png");
    private static final ResourceLocation RL_TEXTURES_DRAGONS_TERRIBLE_TERROR_PAIN_PNG = new ResourceLocation("isleofberk", "textures/dragons/terrible_terror/pain.png");
    private static final ResourceLocation RL_TEXTURES_DRAGONS_TERRIBLE_TERROR_SHARPSHOT_PNG = new ResourceLocation("isleofberk", "textures/dragons/terrible_terror/sharpshot.png");
    private static final ResourceLocation RL_TEXTURES_DRAGONS_TERRIBLE_TERROR_SNEAKY_PNG = new ResourceLocation("isleofberk", "textures/dragons/terrible_terror/sneaky.png");
    private static final ResourceLocation RL_TEXTURES_DRAGONS_TERRIBLE_TERROR_TERRIBLE_TERROR_PNG = new ResourceLocation("isleofberk", "textures/dragons/terrible_terror/terrible_terror.png");
    private static final ResourceLocation RL_TEXTURES_DRAGONS_TERRIBLE_TERROR_TERROR_PNG = new ResourceLocation("isleofberk", "textures/dragons/terrible_terror/terror.png");
    private static final ResourceLocation RL_TEXTURES_DRAGONS_TERRIBLE_TERROR_TITAN_WING_PNG = new ResourceLocation("isleofberk", "textures/dragons/terrible_terror/titan_wing.png");
    private static final ResourceLocation RL_TEXTURES_DRAGONS_TRIPLE_STRYKE_BLUE_PNG = new ResourceLocation("isleofberk", "textures/dragons/triple_stryke/blue.png");
    private static final ResourceLocation RL_TEXTURES_DRAGONS_TRIPLE_STRYKE_BOREAS_PNG = new ResourceLocation("isleofberk", "textures/dragons/triple_stryke/boreas.png");
    private static final ResourceLocation RL_TEXTURES_DRAGONS_TRIPLE_STRYKE_CHAMPION_PNG = new ResourceLocation("isleofberk", "textures/dragons/triple_stryke/champion.png");
    private static final ResourceLocation RL_TEXTURES_DRAGONS_TRIPLE_STRYKE_ECLIPSER_PNG = new ResourceLocation("isleofberk", "textures/dragons/triple_stryke/eclipser.png");
    private static final ResourceLocation RL_TEXTURES_DRAGONS_TRIPLE_STRYKE_NIKORA_TRIPLE_STRYKE_PNG = new ResourceLocation("isleofberk", "textures/dragons/triple_stryke/nikora_triple_stryke.png");
    private static final ResourceLocation RL_TEXTURES_DRAGONS_TRIPLE_STRYKE_ROSETHORN_PNG = new ResourceLocation("isleofberk", "textures/dragons/triple_stryke/rosethorn.png");
    private static final ResourceLocation RL_TEXTURES_DRAGONS_TRIPLE_STRYKE_SLEUTHER_PNG = new ResourceLocation("isleofberk", "textures/dragons/triple_stryke/sleuther.png");
    private static final ResourceLocation RL_TEXTURES_DRAGONS_TRIPLE_STRYKE_SPYRO_PNG = new ResourceLocation("isleofberk", "textures/dragons/triple_stryke/spyro.png");
    private static final ResourceLocation RL_TEXTURES_DRAGONS_TRIPLE_STRYKE_STARSTREAK_PNG = new ResourceLocation("isleofberk", "textures/dragons/triple_stryke/starstreak.png");
    private static final ResourceLocation RL_TEXTURES_DRAGONS_TRIPLE_STRYKE_TRIPLE_STRYKE_PNG = new ResourceLocation("isleofberk", "textures/dragons/triple_stryke/triple_stryke.png");
    private static final ResourceLocation RL_TEXTURES_DRAGONS_ZIPPLEBACK_EXILED_PNG = new ResourceLocation("isleofberk", "textures/dragons/zippleback/exiled.png");
    private static final ResourceLocation RL_TEXTURES_DRAGONS_ZIPPLEBACK_FART_N_SNIFF_PNG = new ResourceLocation("isleofberk", "textures/dragons/zippleback/fart_n_sniff.png");
    private static final ResourceLocation RL_TEXTURES_DRAGONS_ZIPPLEBACK_HAMFEIST_PNG = new ResourceLocation("isleofberk", "textures/dragons/zippleback/hamfeist.png");
    private static final ResourceLocation RL_TEXTURES_DRAGONS_ZIPPLEBACK_HJARTA_PNG = new ResourceLocation("isleofberk", "textures/dragons/zippleback/hjarta.png");
    private static final ResourceLocation RL_TEXTURES_DRAGONS_ZIPPLEBACK_HODD_PNG = new ResourceLocation("isleofberk", "textures/dragons/zippleback/hodd.png");
    private static final ResourceLocation RL_TEXTURES_DRAGONS_ZIPPLEBACK_KANDY_N_KANE_PNG = new ResourceLocation("isleofberk", "textures/dragons/zippleback/kandy_n_kane.png");
    private static final ResourceLocation RL_TEXTURES_DRAGONS_ZIPPLEBACK_LEAF_N_BARK_PNG = new ResourceLocation("isleofberk", "textures/dragons/zippleback/leaf_n_bark.png");
    private static final ResourceLocation RL_TEXTURES_DRAGONS_ZIPPLEBACK_PISTILL_PNG = new ResourceLocation("isleofberk", "textures/dragons/zippleback/pistill.png");
    private static final ResourceLocation RL_TEXTURES_DRAGONS_ZIPPLEBACK_PURPLE_N_NURPLE_PNG = new ResourceLocation("isleofberk", "textures/dragons/zippleback/purple_n_nurple.png");
    private static final ResourceLocation RL_TEXTURES_DRAGONS_ZIPPLEBACK_SANDR_PNG = new ResourceLocation("isleofberk", "textures/dragons/zippleback/sandr.png");
    private static final ResourceLocation RL_TEXTURES_DRAGONS_ZIPPLEBACK_WHIP_N_LASH_PNG = new ResourceLocation("isleofberk", "textures/dragons/zippleback/whip_n_lash.png");
    private static final ResourceLocation RL_ISLEOFBERK_TEXTURES_DRAGONS_LIGHT_FURY_BLUE_GLOW_PNG = new ResourceLocation("isleofberk:textures/dragons/light_fury/blue_glow.png");
    private static final ResourceLocation RL_ISLEOFBERK_TEXTURES_DRAGONS_LIGHT_FURY_PURPLE_GLOW_PNG = new ResourceLocation("isleofberk:textures/dragons/light_fury/purple_glow.png");
    private static final ResourceLocation RL_ISLEOFBERK_TEXTURES_DRAGONS_NIGHT_FURY_NIGHT_FURY_GLOW_PNG = new ResourceLocation("isleofberk:textures/dragons/night_fury/night_fury_glow.png");
    private static final ResourceLocation RL_ISLEOFBERK_TEXTURES_DRAGONS_NIGHT_FURY_SENTINEL_GLOW_PNG = new ResourceLocation("isleofberk:textures/dragons/night_fury/sentinel_glow.png");
}
